version: "3.8"

services:
  gamification:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=0pBrApgLFVf3jwJu4S20O82+VtnnaxA0roooicOjo8Y=.* 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=hammer44*
      - MONGO_URL=mongodb://root:hammer44*@db:27017
      - DB_NAME=lingodyssey
      - RABBITMQ_HOST=kotnikvid:hammer44*@mq:5672
      - LOG_PATH=/var/log/gamification/gamificationLogs.log
    networks:
      - gamification-service
    volumes:
      - ./logs:/var/log/gamification
    depends_on:
      - db
      - mq

  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=hammer44*
    networks:
      - gamification-service
    volumes:
      - mongodata:/data/db

  mq:
    build:
      context: .
      dockerfile: RabbitMQDockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=kotnikvid
      - RABBITMQ_DEFAULT_PASS=hammer44*
    networks:
      - gamification-service
    volumes:
      - mongodata:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    networks:
      - gamification-service
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - gamification-service
    ports:
      - "5601:5601"

  filebeat:
    build:
      context: .
      dockerfile: Dockerfile.filebeat
    container_name: filebeat
    entrypoint: "filebeat -e -strict.perms=false"
    volumes:
      - ./logs:/var/log/gamification
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    networks:
      - gamification-service
    depends_on:
      - gamification
      - elasticsearch

networks:
  gamification-service:

volumes:
  mongodata:
  logs: